### PR TITLE
Query HTTP headers in a case-sensitive manner

### PR DESCRIPTION
**Pull request by alechoey**
protocol-http headers are not isometric. When making a request using protocol-http to construct the request, the header keys that are used to construct the request headers cannot be used to retrieve the header values.

Simple demonstration
```
content_type_header = 'Content-Type'
content_type_value = 'application/json'
hash_headers = { content_type_header => content_type_value }
protocol_headers = Protocol::HTTP::Headers[hash_headers]
raise if protocol_headers[content_type_header] != content_type_value
```

This impacts several use cases:
1. Using adapter-agnostic code in a library like Faraday
2. A tightly coupled client-server implementation in HTTP/1.1
3. Echoing headers from the request into the response in HTTP/1.1

The implementation of headers makes incorrect assumptions that only consider HTTP/2, where headers are serialized in the request in their downcased versions.
* In HTTP/1.1, it is incorrect to optimistically downcase every header when being serialized into the request body
* In HTTP/1.1, it is incorrect to provide **case-sensitive** access to the [response headers](https://www.rfc-editor.org/rfc/rfc9110.html#section-5.1-3).

## Types of Changes

- Bug fix.

## Contribution

- [x] I added tests for my changes.
- [x] I tested my changes locally.
- [x] I agree to the [Developer's Certificate of Origin 1.1](https://developercertificate.org/).

### CODE REVIEW

**Comment by ioquatix** [comment]
Do you think we should encourage users to write `headers['Content-Type']`?

Because, `key.downcase` is not free.

**Comment by alechoey** [comment]
To me, this is not an issue of *encouraging* people to write `headers['Content-Type']`, but instead being able to interoperate with other libraries that are manipulating requests and responses.

In the particular issue I'm running into, I'm using a third-party library that is managing request and response validation for me from an OpenAPI schema. That library happens to use upper-cased header keys. However, that other library isn't doing anything wrong by using capitalized header keys, since they are spec-compliant.

Take for example, [other popular libraries](https://github.com/rack/rack/blob/main/lib/rack/headers.rb#L114-L116) do similar header normalization to be spec-compliant and interop with other libraries.

**Comment by alechoey** [comment]
Here's the more [recent spec](https://www.rfc-editor.org/rfc/rfc9110.html#section-5.1-3) still saying that field names are case-insensitive

**Comment by alechoey** [comment]
@ioquatix I realize you may think this issue is only an issue with developer experience, given your language about encouraging people to use uppercase headers.

I've done a poor job explaining that it's also non-spec-compliant and causes issues for client code that is HTTP version-agnostic.

I've included a few cases where this issue would manifest. If you would like more details on some of those use cases, I am happy to elaborate.

**Comment by zarqman** [comment]
I've run into some issues with header casing as well. However, I've taken a different approach at normalization by monkeypatching `Protocol::HTTP::Headers` to downcase everything upon input/write (in `#initialize` and `#[]=`). All usage of headers is then performed with lowercase, ie: `headers['location']`, and ongoing calls to `downcase` are unnecessary.

This does result in HTTP/1.1 responses using lower-case headers, but that's valid according to the RFCs and clients that can't handle it are out of spec. 

More, there are real world examples of servers responding with a combination of Mixed-Case and lower-case headers (ie: Rails 7.1 with Rack 3 and Puma), so it's unreasonable to assume that inbound HTTP/1.1 responses are Mixed-Case.

I haven't yet run into issues with HTTP/1.1 responses not being universally Mixed-Case, but if I do, the plan is to add a middleware to renormalize to Mixed-Case just before the response is written. Again, if the downstream client is case-sensitive, this would be necessary anyway since an upstream h1 server may or may not provide Mixed-Case headers to begin with.

For context, my use case is a proxy, so I'm dealing with both inbound and outbound headers on both h1 and h2. For just a client app using async-http, universally normalizing to downcase should be fine anyway.

**Comment by alechoey** [comment]
I ended up addressing this by just implementing my own key normalization in my request handling code.

It does mean that my code can't be adapter-agnostic and has to know to use this normalization when using async-http before passing the header values to other packages to be able to query them. It's a a big gotcha when you have to dig through the code, but theoretically `Protocol::Headers` is producing a valid view of the headers that it's receiving from the server.

**Comment by ioquatix** [comment]
Do you mind sharing a link to the normalization you are doing?

**Pull request closed without merging**
